package com.System.EmployeeManagement.exceptionResponseObject;

public enum ExceptionEnum {
	
	EMPLOYEE_NOT_FOUND_EXCEPTION,
	EMPLOYEELIST_NULL_POINTER_EXCEPTION,
	EMPLOYEE_NOT_SAVED_EXCEPTION,
	EMPLOYEE_NOT_REMOVED_EXCEPTION,
	EMPLOEE_NOT_DELETED_EXCEPTION
	
}
